#! /bin/sh

BSPWM_HOME="$(dirname "$0")"

### Workspace names
wscon=''  # console
wsnav=''  # navigator
wsmisc='' # misc
wsgam=''  # game
wsinfo=''

### Configuration
case "$(uname -n)" in
    cherrypc)
        bspc monitor -d "$wscon" "$wsnav" "$wsmisc" "$wsgam"
        ;;
    *)
        bspc monitor primary -d "$wscon" "$wsnav" "$wsmisc"
        ;;
esac
bspc monitor next -d "$wsinfo"

bspc config border_width 1
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config single_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config click_to_focus
bspc config initial_polarity second_child

bspc config external_rules_command "$BSPWM_HOME/rules"

### Monocles
bspc desktop "$wscon" -l monocle
bspc desktop "$wsnav" -l monocle

### Program launch
wallp &
sxhkd -c "$BSPWM_HOME/sxhkdrc" &
picom -b &
bspc rule -a \* -o desktop="$wscon" && emacs ~/doc/notes.org &
bspc rule -a \* -o desktop="$wscon" && term &
command -v > /dev/null spotifyd && spotifyd
xdg-autostart &
