#! /bin/sh

BSPWM_HOME="$(dirname "$0")"

### Workspace names
wscon=''  # console
wsnav=''  # navigator
wsmisc='' # misc
wscomm='' # comm
wsgam=''  # game

wsinfo=''

### Configuration
case "$(uname -n)" in
    CherryPC)
        bspc monitor primary -d  "$wscon" "$wsnav" "$wsmisc" "$wscomm" "$wsgam"
        ;;
    *)
        bspc monitor primary -d  "$wscon" "$wsmisc" "$wsnav"
        ;;
esac

bspc monitor next -d "$wsinfo"

bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config click_to_focus
bspc config initial_polarity second_child

### Rules
bspc config external_rules_command "$BSPWM_HOME/rules"

bspc rule -a Soffice   state=tiled # libreoffice
bspc rule -a Steam     desktop="$wsgam"  follow=off focus=off layer=below
bspc rule -a \*:Steam  desktop="$wsgam"  follow=off focus=off
bspc rule -a Mumble    desktop="$wscomm" follow=off
bspc rule -a discord   desktop="$wscomm" follow=off

### Monocles
bspc desktop "$wsnav" -l monocle

### Program launch
sxhkd -c "$BSPWM_HOME/sxhkdrc" &
dunst &
feh --bg-fill --no-fehbg "$WALLPAPER" &
compton -b &

bspc rule -a \* -o desktop="$wscon" && $TERMINAL &

wmrc &
