#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

wm="$2"
if [ -z "$wm" ]; then
    exit 1
fi
#exec "$wm"
exec bspwm
