export ZPLUG_HOME="$HOME/.config/zplug"

source "$ZPLUG_HOME/init.zsh"
[[ -o interactive ]] &&
    [ -s $BASE16_SHELL/profile_helper.sh ] &&
    eval "$($BASE16_SHELL/profile_helper.sh)"

zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'junegunn/fzf', use:'shell/*.zsh'

if command -v > /dev/null zoxide; then
    eval "$(zoxide init zsh)"
fi

if command -v > /dev/null direnv; then
    eval "$(direnv hook zsh)"
fi

export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'
export HISTSIZE=2000
autoload -Uz compinit
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' menu select
setopt hist_ignore_space hist_reduce_blanks extended_history
setopt inc_append_history_time hist_find_no_dups
setopt promptsubst # interpolate PS1
unsetopt beep

less-widget() {
    BUFFER+=" |& $PAGER"
    zle accept-line
}

zle -N less-widget

bindkey -e # emacs keybindings
bindkey '\eo' less-widget

zplug load
