export BASE16_SHELL="$HOME/.config/base16-shell"
export ZPLUG_HOME="$HOME/.config/zplug"

source "$ZPLUG_HOME/init.zsh"
[[ -o interactive ]] &&
    [ -s $BASE16_SHELL/profile_helper.sh ] &&
    eval "$($BASE16_SHELL/profile_helper.sh)"

[[ -o login ]] && source "$HOME/.profile"

zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'clvv/fasd', use:fasd, as:command

autoload -Uz compinit
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' menu select
setopt hist_ignore_space hist_reduce_blanks extended_history
setopt inc_append_history_time hist_find_no_dups
setopt promptsubst # interpolate PS1
unsetopt beep

bindkey -e # emacs keybindings

zplug load

less-widget() {
    BUFFER+=" |& $PAGER"
    zle accept-line
}

xclip-widget() {
    BUFFER+=" | xclip -i -sel c"
    zle accept-line
}

zle -N less-widget
zle -N xclip-widget
bindkey '\eo' less-widget
bindkey '\ec' xclip-widget
