### ENV
export BASE16_SHELL="$HOME/.config/base16-shell"
export ZPLUG_HOME="$HOME/.config/zplug"

### Source
source "$ZPLUG_HOME/init.zsh"
[[ -o interactive ]] &&
    [ -s $BASE16_SHELL/profile_helper.sh ] &&
    eval "$($BASE16_SHELL/profile_helper.sh)"

source "$HOME/.profile"
source "$ENV"

### Alias
alias -g CLIP='| xclip -i -sel clip'

### Plug
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'clvv/fasd', use:fasd, as:command
zplug 'junegunn/fzf', use:'shell/*.zsh', if:"(( $+commands[fzf] ))", defer:1

### ZSH Settings
autoload -Uz compinit
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' menu select
setopt hist_ignore_space hist_reduce_blanks extended_history
setopt inc_append_history_time hist_find_no_dups
setopt promptsubst # interpolate PS1
unsetopt beep

bindkey -e

zplug load

menu-widget() {
    BUFFER="menu"
    zle accept-line
}

less-widget() {
    BUFFER+=" |& $PAGER"
    zle accept-line
}

zle -N menu-widget
zle -N less-widget
bindkey '\ew' menu-widget
bindkey '\eo' less-widget
